# Form implementation generated from reading ui file 'pyDigitimerNMESForceVoluntary.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_VolunatryMotionWidget(object):
    def setupUi(self, VolunatryMotionWidget):
        VolunatryMotionWidget.setObjectName("VolunatryMotionWidget")
        VolunatryMotionWidget.resize(890, 596)
        self.label_8 = QtWidgets.QLabel(parent=VolunatryMotionWidget)
        self.label_8.setGeometry(QtCore.QRect(550, 20, 291, 17))
        self.label_8.setObjectName("label_8")
        self.VoluntaryforcePlot = PlotWidget(parent=VolunatryMotionWidget)
        self.VoluntaryforcePlot.setGeometry(QtCore.QRect(20, 50, 841, 521))
        self.VoluntaryforcePlot.setObjectName("VoluntaryforcePlot")
        self.pushButtonDefaultTargetForceProfile = QtWidgets.QPushButton(parent=VolunatryMotionWidget)
        self.pushButtonDefaultTargetForceProfile.setGeometry(QtCore.QRect(20, 20, 221, 25))
        self.pushButtonDefaultTargetForceProfile.setObjectName("pushButtonDefaultTargetForceProfile")
        self.pushButtonLoadTargetForceProfile = QtWidgets.QPushButton(parent=VolunatryMotionWidget)
        self.pushButtonLoadTargetForceProfile.setGeometry(QtCore.QRect(260, 20, 221, 25))
        self.pushButtonLoadTargetForceProfile.setObjectName("pushButtonLoadTargetForceProfile")

        self.retranslateUi(VolunatryMotionWidget)
        QtCore.QMetaObject.connectSlotsByName(VolunatryMotionWidget)

    def retranslateUi(self, VolunatryMotionWidget):
        _translate = QtCore.QCoreApplication.translate
        VolunatryMotionWidget.setWindowTitle(_translate("VolunatryMotionWidget", "Volunatry Motion"))
        self.label_8.setText(_translate("VolunatryMotionWidget", "Second Window for NMES Settings & Control Panel"))
        self.pushButtonDefaultTargetForceProfile.setText(_translate("VolunatryMotionWidget", "Reset Default Target Force Profile"))
        self.pushButtonLoadTargetForceProfile.setText(_translate("VolunatryMotionWidget", "Load Target Force Profile"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VolunatryMotionWidget = QtWidgets.QWidget()
    ui = Ui_VolunatryMotionWidget()
    ui.setupUi(VolunatryMotionWidget)
    VolunatryMotionWidget.show()
    sys.exit(app.exec())
